### ISSUE TITLE
dependabot doesn't run CI

### ISSUE THREAD

**Issue by obbardc** [go-debos/test-containers#33]
e.g https://github.com/go-debos/test-containers/pull/32

I think this is caused by the job permissions:
```
jobs:
  build-containers:
    permissions:
      contents: read
      packages: write
```

perhaps we should split the build & push into separate jobs OR simply build the containers always but only push if the `packages` permission is there ?
